version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'

    # セットでアップデートすべきライブラリ群
    groups:
      docusaurus:
        patterns:
          - '@docusaurus/core'
          - '@docusaurus/module-type-aliases'
          - '@docusaurus/plugin-google-gtag'
          - '@docusaurus/preset-classic'
          - '@docusaurus/tsconfig'

    ignore:
      # docusaurus側でバージョンが指定されているため
      - dependency-name: 'rehype-katex'
      - dependency-name: 'remark-math'
