version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '23:00'

    # セットでアップデートすべきライブラリ群
    groups:
      docusaurus:
        patterns:
          - '@docusaurus/core'
          - '@docusaurus/module-type-aliases'
          - '@docusaurus/plugin-google-gtag'
          - '@docusaurus/preset-classic'
